# .gitlab-ci.yml

stages:
  - docker

variables:
  DOCKER_IMAGE: "lv-gitlab.intern.th-ab.de:5050/swa/sose2025/tictactoe-2257738"
  VERSION: "1.0.0"

docker-build-push:
  stage: docker
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $DOCKER_IMAGE:$VERSION -t $DOCKER_IMAGE:latest .
    - docker push $DOCKER_IMAGE:$VERSION
    - docker push $DOCKER_IMAGE:latest
  only:
    - main
    - master